### ISSUE TITLE
React Component

### ISSUE THREAD

**Issue by integratedpartners** [tomwilusz/lord-icon-element#10]
Do you have any plans to release a drop-in react component? Several people I've noticed on forums are keen to use this icon pack but have tried to follow the instructions without success.

**Comment by baszczewski** [comment]
If you are interested in usage with react, it is pretty simple: 
https://github.com/mellson/lord-icon-nextjs-sample

This example use custom element and react component in same time. I am not sure how important is to create react component without dependency of our element because custom element (which we provide) is native technology provided in every mature browser.

**Comment by vitorhpaes** [comment]
I'm using lordicon without nextjs..
When i tryied to use this code to import lordIcon JSON's, returned an error... I tried to use a function inside a useEffect ..
it worked but it is strange. 
I didn't find documentation for de <lord-icon/> element, but i saw somewhere other properties that i can use to change colors, properties of animation.. but without a documentation i have no way of knowing that... 

Now i'm trying to use lottie-react to use icons, but i'm in problems with this library

**Comment by baszczewski** [comment]
Full documentation is available here: 
https://element.lordicon.com/
